server {
    listen 127.0.0.1:8080;
    server_name maas.cti.ugal.ro;

    absolute_redirect off;
    port_in_redirect off;
    server_name_in_redirect off;

    root /var/www/branded-ui;
    index index.html;

    access_log /var/log/nginx/branded-ui.access.log;
    error_log  /var/log/nginx/branded-ui.error.log warn;

    location = / {
        return 301 /MAAS/r/;
    }

    location ~ ^/MAAS/?$ {
        return 301 /MAAS/r/;
    }

    location ~ ^/MAAS/r/assets/(.*)$ {
        try_files /assets/$1 =404;
        add_header Cache-Control "no-store";
    }

    location = /MAAS/r/maas-favicon-32px.png {
        try_files /maas-favicon-32px.png =404;
        add_header Cache-Control "no-store";
    }

    location ~ ^/MAAS/r/(.*)$ {
        try_files /$1 /index.html =404;
        add_header Cache-Control "no-store";
    }

    location ~ /\. {
        return 404;
    }
}
